apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: webapi
          image: gcr.io/my-project/webapi:v1
          ports:
            - containerPort: 7071
        - name: socket
          image: gcr.io/my-project/socket:v1
        - name: timer
          image: gcr.io/my-project/timer:v1
