apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: webapi
          image: eu.gcr.io/noted-palisade-385613/greenhouse-backend_webapi:v2
          ports:
            - containerPort: 7071
        - name: socket
          image: eu.gcr.io/noted-palisade-385613/greenhouse-backend_socket:v2
        - name: timer
          image: eu.gcr.io/noted-palisade-385613/greenhouse-backend_timer:v2
