
services:
  webapi:
    build:
      context: .
      dockerfile: DockerfileWeb
    ports:
      - 7070:7071
  socket:
    build:
      context: .
      dockerfile: DockerfileSocket
  timer:
    build:
      context: .
      dockerfile: DockerfileTimer

    
