services:
  webapi:
    image: 'webapi:latest'
    build:
      context: ./
    ports:
      - 7071:7071
    environment:
      DB_DRIVER: sqlite
      DB_CONNECTION_STRING: "Data Source=Greenhouse.db;Version=3.4;"
  
  sqlite:
    image: 'keinos/sqlite3:latest'
    volumes:
      - ./EfcDataAccess/Greenhouse.db:/Greenhouse.db
