
name: deploy
on:
  push:
    branches:
      - "*"
      - "!main"
jobs:
  push-images:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.5.0
        with:
          project_id: noted-palisade-385613
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}

      - name: Configure Docker
        run: |
          gcloud auth configure-docker --quiet

      - name: Build and Push Docker Images
        run: |
            docker-compose -f docker-compose.yaml build
            docker-compose -f docker-compose.yaml push

      - name: Update image tags
        run: |
            docker tag greenhouse-backend-webapi:latest eu.gcr.io/noted-palisade-385613/greenhouse-backend-webapi:${IMAGE_TAG}
            docker tag greenhouse-backend-socket:latest eu.gcr.io/noted-palisade-385613/greenhouse-backend-socket:${IMAGE_TAG}
            docker tag greenhouse-backend-timer:latest eu.gcr.io/noted-palisade-385613/greenhouse-backend-timer:${IMAGE_TAG}
        env:
            IMAGE_TAG: v2

      - name: Push updated image tags to Google Container Registry
        run: |
            docker push eu.gcr.io/noted-palisade-385613/greenhouse-backend-webapi:${IMAGE_TAG}
            docker push eu.gcr.io/noted-palisade-385613/greenhouse-backend-socket:${IMAGE_TAG}
            docker push eu.gcr.io/noted-palisade-385613/greenhouse-backend-timer:${IMAGE_TAG}
        env:
            IMAGE_TAG: v2