name: main

on:
  push:
    branches:
    - dev-create_automated_deployment
jobs:
  unit_test:
    name: Unit Test
    uses: ./.github/workflows/unit_test.yaml
    secrets: inherit
  publish:
    name: Publish
    uses: ./.github/workflows/push_to_gcr.yaml
    secrets: inherit
  


