name: main

on:
  push:
    branches:
    - dev-create_automated_deployment
jobs:
  push-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.5.0
        with:
          project_id: noted-palisade-385613
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
      - name: Unit Test
        uses: ./.github/workflows/unit_test.yaml
      - name: build_and_deploy
        uses: ./.github/workflows/deploy.yaml
  #deploy_to_ghcr:
  #  name: deploy_to_ghcr
  #  uses: ./.github/workflows/deploy_to_ghcr.yaml
  

