name: main

on:
  push:
    branches:
    - main
jobs:
  unit_test:
    name: Unit Test
    uses: ./.github/workflows/unit_test.yaml
  deploy:
    name: Deploy
    uses: ./.github/workflows/deploy_to_gcr.yaml


