name: main

on:
  push:
    branches:
    - socketInternalTimer-waterSystem_communication

jobs:
  unit_test:
    name: Unit Test
    uses: ./.github/workflows/unit_test.yaml
  build:
    name: Building image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Install EF Core tools
        run: dotnet tool install --global dotnet-ef && echo "::add-path::$(dotnet --info | grep 'Tools directory:' | awk '{print $NF}')"
      - name: EF Core Migrations
        run: dotnet ef database update --project EfcDataAccess --startup-project EfcDataAccess
      - name: DockerHub login
        uses: docker/login-action@v1
        with:
          username:  babicajakub
          password:  ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: babicajakub/greenhouse:latest  
  publish:
    name: Publishing to the cloud
    uses: ./.github/workflows/publish.yaml

