name: main

on:
  push:
    branches:
    - dev-create_automated_deployment
jobs:
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.5.0
      with:
        project_id: noted-palisade-385613
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
      unit_test:
        name: Unit Test
        uses: ./.github/workflows/unit_test.yaml
      build_and_deploy:
        name: Build and Deploy
        uses: ./.github/workflows/deploy.yaml
  #deploy_to_ghcr:
  #  name: deploy_to_ghcr
  #  uses: ./.github/workflows/deploy_to_ghcr.yaml
  

