name: main

on:
  push:
    branches:
    - dev-create_automated_deployment
jobs:
  unit_test:
    name: Unit Test
    uses: ./.github/workflows/unit_test.yaml
  build_and_deploy:
    name: Build and Deploy
    uses: ./.github/workflows/deploy.yaml
  #deploy_to_cluster:
  #  name: deploy to cluster
  #  uses: ./.github/workflows/deploy_to_cluster.yaml
  #deploy_to_ghcr:
  #  name: deploy_to_ghcr
  #  uses: ./.github/workflows/deploy_to_ghcr.yaml
  

