name: main

on:
  push:
    branches:
    - main
jobs:
  unit_test:
    name: Unit Test
    uses: ./.github/workflows/unit_test.yaml
    secrets: inherit
  publish:
    name: Publish
    uses: ./.github/workflows/push_to_gcr.yaml
    secrets: inherit
  publish_test_coverage:
    name: Publish coverage
    uses: ./.github/workflows/publish-coverage.yaml
    secrets: inherit


