name: Test Coverage Deployment

on:
  push:
    branches:
      - dev-TestCoverageWorkflow

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and run tests
        run: |
          dotnet build
          dotnet test --collect:"XPlat Code Coverage" --results-directory:"./UnitTest/TestResults"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: coverage-report
          publish_branch: gh-pages