name: Test Coverage Deployment

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and run tests
        env:
          EMAIL_USERNAME: ${{ secrets.EMAIL }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: |
          dotnet build
          dotnet test --collect:"XPlat Code Coverage" --results-directory:"./Tests/TestResults"

      - name: Generate coverage report
        run: |
          dotnet tool install -g dotnet-reportgenerator-globaltool
          reportgenerator "-reports:./Tests/TestResults/**/coverage.cobertura.xml" "-targetdir:./Tests/TestResults/coverage-report" -classfilters:'-SocketClient.*;-Program' -reporttypes:Html_Light

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.CR_PAT }}
          publish_dir: ./Tests/TestResults/coverage-report
          publish_branch: gh-pages
