name: Publish to GCR and GHCR

on:
  workflow_call:
  
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
   
      - id: auth
        uses: google-github-actions/auth@v1
        with:
            credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}   
            
      - name: Login to GCR
        env:
          PROJECT_ID: noted-palisade-385613
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Build Docker Image
        env:
          IMAGE_NAME: greenhouse_v3
          PROJECT_ID: noted-palisade-385613
        run: docker build -t $IMAGE_NAME:latest .

      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet

      - name: Push Docker Image to Container Registry GCR
        env:
          IMAGE_NAME: greenhouse_v3
          PROJECT_ID: noted-palisade-385613
        run: |-
          docker tag $IMAGE_NAME:latest eu.gcr.io/$PROJECT_ID/$IMAGE_NAME:latest 
          docker push eu.gcr.io/$PROJECT_ID/$IMAGE_NAME:latest 

      - name: Extract metadata (tags, labels) for Docker GHCR
        env:
          REGISTRY: ghcr.io
          IMAGE_NAME: ${{ github.repository }}
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
