name: Test Coverage Deployment

on:
  push:
    branches:
      - dev-TestCoverageWorkflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.2.3'  # Replace with the desired .NET version

      - name: Build and run tests
        run: |
          dotnet build
          dotnet test --collect:"XPlat Code Coverage" --results-directory:"./TestResults"  # Replace with your MSTest command

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./TestResults  # Replace with 