name: Publish to GCR and GHCR
# create simple trigger based on everytime we make change to this repository
on:
  workflow_call:
#define jobs
jobs:
  Deploy:
    runs-on: ubuntu-latest #run this workflow on ubuntu instance
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1 #checkouts your repo, so this workflow can access it
      - name: Log in to GHCR
        env:
          REGISTRY: ghcr.io #create env called REGISTRY
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }} #parse REGISTRY env value to here. Make sure it is correctly stating ghcr.io
          username: ${{ github.actor }} #this will be our github account
          password: ${{ secrets.GITHUB_TOKEN }} #parse the value of repository secret called CR_PAT that we have created earlier

      - name: Extract metadata (tags, labels) for Docker GHCR
        env:
          REGISTRY: ghcr.io
          IMAGE_NAME: ${{ github.repository }}
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} #create ghcr image format within as id called meta
      - name: publish
        uses: pennsignals/publish_docker-compose@v0.1.0
        with:
          docker_compose: docker-compose.yaml # required
          repo_token: ${{ secrets.GITHUB_TOKEN }}
    #  - name: Build and push Docker image
     #   uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc #push docker image to ghcr
      #  with:
       #  context: .
        # push: true
         #tags: ${{ steps.meta.outputs.tags }}
         #labels: ${{ steps.meta.outputs.labels }}