name: Test pushed commits
on:
  push:
    branches:
      - "*"
      - "!main"
jobs:
  unit_test:
    name: Unit Test
    uses: ./.github/workflows/unit_test.yaml
    secrets: inherit
  docker_compose:
    name: Docker Compose
    uses: docker/compose-action@v1
    run: |
      docker-compose build
      docker-compose up
      