name: Unit Test
on:
  workflow_call:
jobs:
  tests:
    env:
      EMAIL_USERNAME: ${{ secrets.EMAIL }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Tests
        run: dotnet test
