name: Unit Test
on:
  workflow_call:
jobs:
  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Debug Environment Variables
        run: |
          echo "EMAIL_USERNAME: $EMAIL_USERNAME"
          echo "EMAIL_PASSWORD: $EMAIL_PASSWORD"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Tests
        run: dotnet test
